version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2023.05.0
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8050:80/tcp"
    environment:
      TZ: 'Europe/Amsterdam'
      PIHOLE_DNS_: 9.9.9.9;1.1.1.1
      ServerIP: 192.168.178.61
      QUERY_LOGGING: 'false'
      VIRTUAL_HOST: pihole.martijnbunschoten.nl
    # Volumes store your data between container upgrades
    volumes:
      - './data/etc-pihole/:/etc/pihole/'
      - './data/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: always
    networks:
      dns-pihole:
        ipv4_address: 172.29.0.100

networks:
  dns-pihole:
   external: true