apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: proxmox.martijnbunschoten.nl
  namespace: cert-manager
spec:
  secretName: proxmox.martijnbunschoten.nl
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "proxmox.martijnbunschoten.nl"
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer